version: "2"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytardis-app-mydata
    volumes:
      - .:/app/tardis/apps/mydata
    environment:
      - CODECOV_TOKEN
      - GITHUB_SHA
